name = "capture"
name_pretty = "Capture"
fixed_order = true

[[entries]]
text = "Screenshot - Region"
icon = " 󰹑 "
actions = { region = "uwsm app -- hyprshot -m region" }

[[entries]]
text = "Screenshot - Window"
icon = " 󰹑 "
actions = { window = "uwsm app -- hyprshot -m window" }

[[entries]]
text = "Record Screen"
icon = "  "
actions = { record = "uwsm app -- obs --startrecording" }
