name = "hyprnosismenu"
name_pretty = "hyprnosis menu"
fixed_order = true

[[entries]]
text = "Apps"
icon = "  "
actions = { apps = "walker" }

[[entries]]
text = "Power"
icon = "  "
actions = { power = "walker --provider menus:power" }

[[entries]]
text = "Update"
icon = "  "
actions = { update = "walker --provider menus:updates" }

[[entries]]
text = "Packages"
icon = "  "
actions = { packages = "walker --provider menus:packages" }

[[entries]]
text = "Theme"
icon = "  "
actions = { theme = "~/.config/hyprnosis/modules/theme_changer.sh" }

[[entries]]
text = "Wallpaper"
icon = " 󰸉 "
actions = { wallpaper = "~/.config/hyprnosis/modules/wallpaper_changer.sh" }

[[entries]]
text = "Utilities"
icon = "  "
actions = { utilities = "walker --provider menus:utilities" }

[[entries]]
text = "Learn"
icon = "  "
actions = { learn = "walker --provider menus:learn" }
