name = "style"
name_pretty = "Style"
fixed_order = true

[[entries]]
text = "Theme"
icon = "  "
actions = { theme = "walker --provider menus:themes" }

[[entries]]
text = "Wallpaper"
icon = " 󰸉 "
actions = { theme = "walker --provider menus:wallpapers" }
