name = "updates"
name_pretty = "Updates"
fixed_order = true

[[entries]]
text = "Update System Packages"
icon = "  "
actions = { updatesystem = "ghostty -e ~/.config/hyprnosis/modules/updates/update_system.sh" }

[[entries]]
text = "Update AUR Packages"
icon = "  "
actions = { updateaur = "ghostty -e ~/.config/hyprnosis/modules/updates/update_aur.sh" }

[[entries]]
text = "Update hyprnosis"
icon = "  "
actions = { updatehyprnosis = "ghostty -e ~/.config/hyprnosis/modules/updates/update_hyprnosis.sh" }
