name = "utilities"
name_pretty = "Utilities"
fixed_order = true

[[entries]]
text = "Capture"
icon = " 󰹑 "
actions = { capture = "walker --provider menus:capture" }

[[entries]]
text = "Configure Hyprland"
icon = "  "
actions = { hyprconf = "ghostty -e ~/.config/hyprnosis/modules/quickconfig/quickconfig.sh" }

[[entries]]
text = "Manage Services"
icon = "  "
actions = { capture = "walker --provider menus:capture" }

