name = "utilities"
name_pretty = "Utilities"
fixed_order = true

[[entries]]
text = "Capture"
icon = " 󰹑 "
actions = { capture = "walker --provider menus:capture" }

[[entries]]
text = "Configure Hyprland"
icon = "  "
actions = { hyprconf = "ghostty -e ~/.config/hyprnosis/modules/quickconfig/quickconfig.sh" }

[[entries]]
text = "Restart Waybar"
icon = " 󰜉 "
actions = { waybar = "systemctl --user restart waybar.service" }

[[entries]]
text = "Restart Walker"
icon = " 󰜉 "
actions = { walker = "systemctl --user restart walker.service" }

[[entries]]
text = "Restart Elephant"
icon = " 󰜉 "
actions = { waybar = "systemctl --user restart elephant.service" }
